### ISSUE TITLE
OSM-US Spring Hackathon May 21-22

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-planning#19]
Opening this ticket for brainstorming and ideas around the OSM-US Spring Hackathon May 21-22!

**Comment by bhousel** [comment]
We've planned a loose agenda for the Hackathon with a few proposed themes.  You can work on these, or choose your own adventure ⚔️

---

### Monday
9:00a Intro & Goal Setting - Maggie and Bryan from OSM US

9:30a Work  
(Theme:  Choosing Imagery)

12:00p Lunch with the Mapbox Team

1:00p Work  
(Theme:  Welcoming New Users)

5:30p Wrap-up
6:00p Dinner

### Tuesday 
9:00a Intro & Goal Setting - Maggie and Bryan from OSM US

9:30a Work 
(Theme:  Education / Task Management)

12:00p Pizza

1:00p Work  
(Theme:  Translation / Localization)

5:30p Wrap-up
6:30p Dinner / Social (TBD)

**Comment by mcawley** [comment]
Productive imagery conversation this morning - follow here: https://github.com/osmlab/osm-planning/issues/18

**Comment by mcawley** [comment]
Conversation around welcoming new mappers starting now! https://github.com/osmlab/osm-planning/issues/13

**Comment by bhousel** [comment]
Adding YouthMappers to osm-community-index tracked here:  https://github.com/osmlab/osm-community-index/issues/152

**Comment by bhousel** [comment]
We believe several of the Top 10 Tasks can be done easier with vector tiles support on osm.org - kicking off discussion here:  https://github.com/openstreetmap/operations/issues/214

**Comment by bhousel** [comment]
We did some investigation into replacing Overpass Turbo with OSMCha in the [TeachOSM grading workflow](http://teachosm.org/en/workflow/workflow5).

We ran into issues for OSMCha with logging in - this was related to a server SSL cert / OAuth.

@geomantic reviewed and while most of the functionality is present in OSMCha, it lacks the ability to provide feature counts - for example, # of buildings added.  Might be able to make up this functionality by using Missing Maps.

Opened this issue https://github.com/mapbox/osmcha-frontend/issues/296  but it turned out to be caused by a browser extension.

**Comment by mmd-osm** [comment]
> We did some investigation into replacing Overpass Turbo with OSMCha in the TeachOSM grading workflow.

I'd suggest to improve that Overpass Turbo section a bit. With 0.7.55 you can easily do a break down for a whole lot of students without resorting to manually counting them one by one.  -- https://github.com/drolbr/Overpass-API/issues/395#issuecomment-377238317

Here's an example to get the number of nodes, ways, relations per user in the current bounding box:

```
[bbox:{{bbox}}];
nwr;
for(user())
{
   make stat "user" =_.val,
             count_nodes = count(nodes),
             count_ways = count(ways),
             count_rels = count(relations);
   out;
};
```

http://overpass-turbo.eu/s/z0Q

Restricting the list of students to the ones you're interested in:

```
[bbox:{{bbox}}];
nwr(user:mvexel,nyuriks,oanac2_telenav);
for(user())
{
   make stat "user" =_.val,
             count_nodes = count(nodes),
             count_ways = count(ways),
             count_rels = count(relations);
   out;
};
```

Of course you can also count buildings only, or anything else for that matter.

```
[bbox:{{bbox}}];
nwr[building];
for(user())
{
   make stat "user" =_.val,
             count_nodes = count(nodes),
             count_ways = count(ways),
             count_rels = count(relations);
   out;
};
```

**Comment by bhousel** [comment]
Thanks @mmd-osm!  We're looking into whether this would help with the workflow. I think the TeachOSM folks still need to do the counts _per user_ since each user is getting a grade for their work.  But if a teacher wanted to see a summary of all the work done in an area, this would be helpful.

**Comment by mmd-osm** [comment]
@bhousel : ahem, counts _are_ per user, that's exactly the purpose of my examples :sunglasses:

**Comment by bhousel** [comment]
> ahem, counts are per user, that's exactly the purpose of my examples 😎

oh - I see now! Could we run this query for a defined set of users?

**Comment by mmd-osm** [comment]
Sure, see the second example: `nwr(user:mvexel,nyuriks,oanac2_telenav);` or `nwr(user:student1,student2,student3,student4);`

nwr is just an abbreviation for node, way and relation (saves a bit of typing).

**Comment by mmd-osm** [comment]
I don't know exactly if there's a follow up for the TeachOSM changes. In any case, If they're stuck with the Overpass stuff to gather some statistics or use a different output mode (like CSV for Excel import),  creating a Github issue for it and adding a @mmd-osm mention would be an option.

**Comment by shawnmgoulet** [comment]
@bhousel @geomantic how to grade contributions is always a top inquiry from educators. This is an important topic.

@mmd-osm - thank you for sharing this code - this is exactly the information most teachers want (individual statistics and all students statistics). :metal:

The TeachOSM site will be undergoing a redesign soon and will be sure to include this. However, teachers sometimes find query languages bothersome.

I do think it's a valuable activity for students (composing & understanding data queries).

Some type of interactive, user input interface to execute the queries would be helpful for some teachers. Maybe that would fit into overpass's plans or would have to be implemented elsewhere.
