### ISSUE TITLE
Who plans to be at State of the Map 2019, Heidelberg, Germany?

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-planning#24]
_From @tordans on January 11, 2019 11:32_

I wonder who of those that are active here will be at https://2019.stateofthemap.org/ ?
Maybe we could do a session to work on some part of iD. Some code? Or some wireframing?

>STATE OF THE MAP
September 21 – 23
>
>ADDITIONAL EVENTS
HOT Summit
September 19 – 20

PS: This might be the wrong place for this question :). Maybe move it to https://github.com/osmlab/osm-planning ?

_Copied from original issue: openstreetmap/iD#5696_

**Comment by tordans** [comment]
@bhousel will you be there? Are any iD Topic planned?

(Thanks for moving the issue.)

**Comment by bhousel** [comment]
I'm not sure yet - but my main areas of focus for iD this year is adding robust validation, integration with QA and tasking tools, and adding a simple import tool.

Aside from those, there are a lot of issues in iD that I would love help with.  I know that people want to work on fun new stuff, but sometimes a bigger impact can be made by improving localization, test coverage, performance, and fixing bugs.  Those contributions are really the most important for a mature project like iD that is more maintenance than new development..
