### ISSUE TITLE
Delete osmlab/osm-planning

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-planning#25]
Hi!  This project has kind of gone stale, and I've decided I don't really want to keep it going anymore.  If anyone is interested in seeing it continue, please let me know and I'm happy to grant admin access to whoever wants it.  Otherwise, I'll delete it in a week.  Thanks ✌️

**Comment by 1ec5** [comment]
Please consider archiving this repository instead of deleting it. During its short lifespan, this repository has collected some pretty good ideas. Archiving the repository preserves the historical context without becoming a burden on maintainers.

**Comment by joostschouppe** [comment]
If no-one else volunteers, you can give the admin rights to me. I really like this place and this effort, even though I agree that it's getting a bit stale. But I think that has more to do with us being incredibly slow on some of this stuff, not because it might be an irrelevant place.

**Comment by bhousel** [comment]
ok! @joostschouppe is the admin now 👍
