### ISSUE TITLE
subscribe to an OSM object

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/osm-planning#6]
## I am proposing...

Subscribe to changes of individual objects in OSM

### What will this enable that we can't do today?

Currently you can signup for notifications of all changes within an area, but there is no way for less notifications. I might only want to receive a note when someone changes something I've edited in the past, or a feature important to me eg. local cycle way is changed.

Just like GitHub will subscribe you to any issue or pr you comment in.

### Whom does this benefit?

Who are the end users? mappers
Beginners / Power Users? all. Beginers would recieve a note when something they changed is changed, and in tern makes them better mappers by seeing someone fix up any bad tagging. Power users would be able to monitor things they know about to identify bad edits faster.

### Any drawbacks?

Might be too many notifications, but still much less noisy than using the bbox RSS feed.

### Resources needed to build and maintain?

Who will build this?
Need a database / hosting?
Independent project or run on OpenStreetMap infrastructure? It would have the most reach if integrated directly on OSM.org, but would be possibly as a 3rd party service. Didn't receive much love when posted at https://github.com/openstreetmap/openstreetmap-website/issues/1454

### See also:

https://github.com/openstreetmap/openstreetmap-website/issues/1454

### Describe this project in a single emoji:

:bell:

**Comment by grischard** [comment]
Is this a bit like what https://osm-hall-monitor.herokuapp.com/ does, with a bbox or a query? I've also wanted to have something like that, e.g. for admin boundaries.

**Comment by andrewharvey** [comment]
> Is this a bit like what https://osm-hall-monitor.herokuapp.com/ does, with a bbox or a query? I've also wanted to have something like that, e.g. for admin boundaries.

That's awesome! For some reason I couldn't get it to work when I tried it a while back, but it's working now and it's pretty much exactly what I was looking for. You can subscribe to an OSM Object, User, or Tag. I think this is pretty much solved now.
