### ISSUE TITLE
Moderation queue

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-planning#8]
from https://wiki.openstreetmap.org/wiki/Top_Ten_Tasks#Moderation_queue

### Moderation queue
* What's involved: Ruby on Rails
* What's being done already? https://github.com/openstreetmap/openstreetmap-website/pull/1576

The OpenStreetMap website, including diaries, the map, user notes and other services, has to deal with spam and abusive content in various forms. Currently, people are reporting it to admins via IRC channels or by mail. As the community grows, we need a better way.

A long-requested solution for this problem is a moderation queue. From the website user's perspective, this is basically a "Report" button next to everything. The goal is to offer moderators a queue of reports from every service on the OSM website, allowing them to ignore or act on a report.

Work on this feature goes back at least to a Google Summer of Code project in 2014 with some more details available [here](https://github.com/openstreetmap/openstreetmap-website/issues/841). Unfortunately, the student did never finish his work in a way that would have allowed for this code to be be merged. And while it has been picked up again in the past [here](https://github.com/openstreetmap/openstreetmap-website/pull/1268) and more recently [here](https://github.com/openstreetmap/openstreetmap-website/pull/1576) by @gravitystorm, this is still an open task that is a high priority for many.

---
_This issue comes from the [OSM Top Ten Tasks](https://wiki.openstreetmap.org/wiki/Top_Ten_Tasks) page_

**Comment by mmd-osm** [comment]
This one can be closed. Moderation queue is in production.

**Comment by bhousel** [comment]
> This one can be closed. Moderation queue is in production.

Nice!
